### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by DanielOaks** [bibanon/BASC-py4chan#1]
Just an issue to keep track of the documentation. I've setup a docs page with ReadTheDocs [here](http://basc-py4chan.readthedocs.org/en/latest/index.html), and it's progressing quite well.

I'm focusing more on the API side of things right now, but I'll flesh out the documentation proper and provide some good stuff for it.

**Note:** With the new documentation I've changed the docstring format to match Google's recommendation, because it looks and plays a lot nicer with Sphinx.

**Comment by antonizoon** [comment]
I now understand how to use the documentation, and it seems very good for anyone who wants to try it out.
