### ISSUE TITLE
So many aliases!

### ISSUE THREAD

**Issue by DanielOaks** [bibanon/BASC-py4chan#4]
Just the general presence of aliases scattered throughout the code, eg:

```python
board = Board
number = num = no = post_number
html_comment = orig_comment
body = text = comment
url = post_url
url = thread_url
semantic_url = semantic_thread_url
```

I think we can cull most of them, personally. Especially now that the docs are actually getting written up. I'm thinking of culling all of these or changing it so that just one attribute is provided in place of the multitude of aliases.

-------

The `board/Board` one just seems a bit unnecessary to me. Mostly because classes in Python start with uppercase letters, and especially given that it prevents access to the actual board.py module.

--------

We'll change both `post_url` and `thread_url` to just `url` for both objects. Given the object-oriented nature of the library, we shouldn't need to worry about people getting confused. Eg:

```
<Thread>.url   vs   <Thread>.thread_url
<Post>.url   vs   <Post>.post_url
```

The second one seems a bit redundant, and given that it simplifies the interface and makes it more consistent between different objects, it makes sense to just combine them.

`semantic_thread_url` will be changed to `semantic_url` in the same vain, no need for the `thread_` qualifier since it's an attribute of a Thread object.

--------

Comments are a bit weird. We've got HTML comments, or Raw comments, and then 'cleaned' or plaintext comments. I'm thinking remove the aliases, and just have the following attributes on Post objects:

* **html_comment**: The comment exactly as it is, <wbr> tags in the middle of URLs and all that stuff.
* **comment**: The comment exactly as-is, with the <wbr> tags stripped out.
* **text_comment**: What are currently known as 'cleaned' comments.

Doing this (separating them out like this into separate attributes) also stops the user from having to decide whether to 'clean' comments when they first initialize the Board object, which does seem a bit out-of-place being there anyway.

--------

So, I'll probably end up doing that in the next day or two, but I'll float it here first and see what you guys think.

**Comment by antonizoon** [comment]
It seems like the majority of the aliases have been culled, with the exception of `board = Board` and `is_op = is_OP`. Good job.
